version: "3.4"

services:

  server:
    build:
      target: final-server
      args:
        RUST_VERSION: 1.75.0
        WASM_TAG: v0.1.0
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    restart: unless-stopped

  consumer-delay:
    build:
      context: .
      target: final-consumer
    env_file:
      - .env.docker
    command: ["template-consumer", "--consumer", "delay"]
    restart: unless-stopped

  consumer-dto:
    build:
      context: .
      target: final-consumer
    env_file:
      - .env.docker
    command: ["template-consumer", "--consumer", "dto"]
    restart: unless-stopped

  consumer-state:
    build:
      context: .
      target: final-consumer
    env_file:
      - .env.docker
    command: ["template-consumer", "--consumer", "state"]
    restart: unless-stopped

  eventstore:
    image: eventstore/eventstore:24.2.0-bookworm-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_EXT_IP=0.0.0.0
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  redis:
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"


volumes:
  eventstore-volume-data:
  eventstore-volume-logs: