[package]
name = "template-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gyg-eventsource = { workspace = true }
serde = { workspace = true }
eventstore = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
template-shared = { path = "../shared" }
template-state = { path = "../state" }
rocket = { workspace=true, features = ["json"] }
serde_json = "1"
anyhow = "1.0"