name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
#      - name: Run tests
#        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy -- -D clippy::expect_used -D clippy::panic  -D clippy::unwrap_used